version: "3.3"
services:
  moo-webserver:
    image: gchr.io/${GITHUB_REPOSITORY_OWNER}/moo-webserver
    build: webserver

  moo:
    depends_on:
      - moo-webserver
    image: ghcr.io/${GITHUB_REPOSITORY_OWNER}/moo
    build: moo
    entrypoint: [ "/bin/bash", "testing.sh" ]
