version: "3.3"
services:
  moo-webserver:
    image: ghcr.io/${GITHUB_REPOSITORY_OWNER}/moo-webserver
    build:
      context: webserver
      x-bake:
        cache-from:
          - type=gha,scope=moo-webserver
        cache-to:
          - type=gha,mode=max,scope=moo-webserver

  moo:
    depends_on:
      - moo-webserver
    image: ghcr.io/${GITHUB_REPOSITORY_OWNER}/moo
    build:
      context: moo
      x-bake:
        cache-from:
          - type=gha,scope=moo
        cache-to:
          - type=gha,mode=max,scope=moo
    entrypoint: [ "/bin/bash", "/tmp/moo/testing.sh" ]
