name: Moo

on:
  push:
    branches:
      - main
    workflow_dispatch:

jobs:
  tests:
    name: moo
    runs-on: ubuntu-latest
    env:
      REGISTRY: ghcr.io

    steps:
      - name: checkout code
        uses: actions/checkout@v3

      # - name: log into github container registry
      #   uses: docker/login-action@v2
      #   with:
      #     registry: ghcr.io
      #     username: ${{ github.actor }}
      #     password: ${{ secrets.GITHUB_TOKEN }}

      # I haven't yet figured out a way to get github actions to
      # pull from and push to a registry.
      # So, for now, we have to rebuild the docker image every time
      # we run a test, which is profligate and slow, but it's what
      # we're stuck with for now.  At least running the tests on
      # your local checkout can be efficient.
      
      - name: run test
        run: |
          docker compose build
          docker compose run moo
