name: Moo

on:
  workflow_run:
    workflows: ["Build and Run"]
    branches: [main]
    types:
      - completed
  workflow_dispatch:

jobs:
  tests:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    name: moo
    runs-on: ubuntu-latest
    env:
      REGISTRY: ghcr.io

    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: log into github container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: run test
        run: |
          docker compose pull
          docker compose run moo
