name: Moo

on:
  push:
    branches:
      - main
    workflow_dispatch:



jobs:
  tests:
    name: moo
    runs-on: ubuntu-latest
    env:
      REGISTRY: ghcr.io

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log into github container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Hello world
        run: echo first ${{ github.repository_owner }} second ${GITHUB_REPOSITORY_OWNER}

      - name: Build and push moo docker image
        uses: docker/build-push-action@v2
        with:
          pull: true
          push: true
          load: true
          tags: ghcr.io/${{ github.repository_owner }}/moo:latest
          context: .

      - name: Run test
        run: docker compose run moo
