name: Moo

on:
  push:
    branches:
      - main
    workflow_dispatch:

jobs:
  tests:
    name: moo
    runs-on: ubuntu-latest
    env:
      REGISTRY: ghcr.io

    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: log into github container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: build and push moo docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          pull: true
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/moo:latest

      - name: run test
        run: docker compose run moo
