name: Moo

on:
  push:
    branches:
      - main
    workflow_dispatch:

jobs:
  tests:
    name: moo
    runs-on: ubuntu-latest
    env:
      REGISTRY: ghcr.io

    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: log into github container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: setup docker buildx
        uses: docker/setup-buildx-action@v2
        with:
          driver: docker-container

      - name: cache docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-citest-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-citest-
         
      - name: bake
        uses: docker/bake-action@v2.3.0
        with:
          load: true
      # When I do this, it always rebuilds at least
      #  one of the two images in the compose file.
      # I don't understand why.
      # Instead, I have to put cache in the compose file.
      #     set: |
      #       *.cache-from=type=local,src=/tmp/.buildx-cache
      #       *.cache-to=type=local,mode=max,dest=/tmp/.buildx-cache-new
            
      - name: run test
        run: |
          docker compose run moo

      # Do this to avoid the cache continuously growing
      - name: move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache
         
